[package]
name = "portfolio_game_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"
rand = "0.8.5"
tokio-util = "0.7.14"
